ROOT := ../../..
OBJS := ${patsubst %.c,%.o,${filter %.c, ${SRC}}}
OUT := ${ROOT}/lib/modules/${OUT}

%.o: %.c
	gcc -I${ROOT}/include -c -fpic $<
all: ${OBJS}
	gcc -shared -o ${OUT} *.o
syms:
	@objdump -e ${OUT} -TS
