SRC   := stats.c
OUT   := stats.so

# * End config * #                                                                                                                                                        
include ../Makefile.module
