SRC   := party.c follow.c
OUT   := party.so

# * End config * #                                                                                                                                                      

include ../Makefile.module

